### ISSUE TITLE
compatibility with other mods

### ISSUE THREAD

**Issue by Manuelita00** [Micaxs/smokeleafindustry#18]
I’m playing Minecraft with smokerleaf industry mod and Mineccraft comes alive mod and I can’t seem to find any weed dealer structure. I don’t know how to turn a villager into a weed dealer and the only plant I can grow is the white widow.

**Comment by Micaxs** [comment]
The dealer structure is found within vanilla plains biome's.

The Point of Interest for the weed dealer is currently a Hemp Planks which you should be able to make with just having access to white widow in case the issue persists of not able to find any structure.
